clear all

load('C:\Users\zhangl33\Projects\Project-SLMonlineControl\subfun\Color\colorMapPN3');
% Folder='E:\LuSLMOnlineTest\SL0777-Ai203\12032024\SingleP\Top5SpeedStimEdgeExc\Data\TSeries-12032024-1335-010\';
load('E:\LuSLMOnlineTest\SL0777-Ai203\12182024\SingleP\Top12SpeedStimEdgeExc\SLMIncludedIndFromIscell.mat');
% BinFile='E:\LuSLMOnlineTest\SL0777-Ai203\12032024\SingleP\Top5SpeedStimEdgeExc\Data\TSeries-12032024-1335-010.bin';


ProcessFolder='E:\LuSLMOnlineTest\SL0777-Ai203\12182024\SingleP\Top12SpeedStimEdgeExc\';
load([ProcessFolder 'SLMIncludedIndFromIscell.mat'])

DataFolder=[ProcessFolder 'Data\'];
SumDataFolder=[ProcessFolder 'DataSum\'];
mkdir(SumDataFolder);
PreSLMCal=15;
PostSLMCal=3;
MPFrameJump=1;
NeighbourHfWidthPixel=20;

planeDepth=round(confSet.scan_Z(1)+confSet.ETL);




temp=dir([DataFolder 'TSeries*.bin'])
% Get all .bin files matching the pattern

% Convert filenames to lowercase for consistent comparison
file_names = lower({temp.name});  % Convert to cell array of lowercase filenames

% Filter files that do not end with 'raw.bin' or 'corr.bin'
matching_files = file_names(~(endsWith(file_names, 'raw.bin') | endsWith(file_names, 'corr.bin')));

% Convert to full paths if needed
%matching_files = fullfile({matching_files.folder}, {matching_files.name});

%%
binName=matching_files;
binName(25)=[];





tifFolder=binName;
matName=binName;
for i=1:length(tifFolder)
    tifFolder{i}=tifFolder{i}(1:end-4);
    matName{i}=[matName{i}(1:end-4) '.mat'];
end

pattern = '-(\d{3})$';
    % Loop through each row in the table to extract the FileID
for i = 1:length(tifFolder)
        % Extract the name
    nameStr = tifFolder{i};
        % Use regexp to extract the 3-digit number and convert to numeric
    tokens = regexp(nameStr, pattern, 'tokens');

    if ~isempty(tokens)
       fileIDList(i,1) = str2double(tokens{1}{1});
    end
 end

%%% [tSeriesIterID XMLparam.Point XMLparam.Laser XMLparam.RoundID PSTHparam.TargetPos] Old structure



%%
clear Temp
Ziteration = 11;
ZseriesL = repmat(31, 1, length(fileIDList));

OutTBLAll=[];
PSTHtraceAll=[];
for iFile=1:length(binName)
    

    TZseriesBin=repmat(ZseriesL(iFile),1,Ziteration);
    TZseriesUpdate=[TZseriesBin(1) TZseriesBin(2:end)-1]; %%Update of Zseries repetition as the 1st frame of Z (syn. with MP) is deleted. Noted that 1st Zseries is not syn. with MP
    frameBeforeSLM=cumsum(TZseriesUpdate(1:end-1))';
    % PostStimI=frameBeforeSLM(iPoint)+[1:PostSLMFrameN];
    % PreStimI=frameBeforeSLM(iPoint)-PreSLMFrameN+1:frameBeforeSLM(iPoint);
    load([DataFolder matName{iFile}]);

    % tic
    clear OutTBL
    OutTBL=MPSeqFolder_1TargetXNon([DataFolder tifFolder{iFile} '\'],confSet,Pos3Dneed);
    frameBeforeSLM=frameBeforeSLM((OutTBL.markCycle-1)/ZseriesL(iFile));       %%In case some MP does not excute correctly.


    OutTBL.FileID=fileIDList(iFile)*ones(size(OutTBL,1),1);
    OutTBLAll=[OutTBLAll;OutTBL];
    planePos=round(Pos3Dneed(OutTBL.Point,3));
    [~,planeI]=ismember(planePos,planeDepth);

    Suite2pData=load([DataFolder matName{iFile}]);
    TestingNeuronData=Suite2pData.DeltaF(SLMIncludedIndFromIscell,:);


    for iP=1:size(OutTBL,1)
        Point=OutTBL.Point(iP);
        PostStimI=frameBeforeSLM(iP)+[1:PostSLMCal];
        PreStimI=frameBeforeSLM(iP)-PreSLMCal+1:frameBeforeSLM(iP);
        PSTHtrace=TestingNeuronData(Point,[PreStimI PostStimI]);
        PSTHtraceAll=[PSTHtraceAll;PSTHtrace];
    end


   % toc
end


PSTHTraceN=PSTHtraceAll;
PSTHtraceBase=repmat(mean(PSTHtraceAll(:,1:PreSLMCal),2),1,size(PSTHtraceAll,2));
PSTHTraceN=PSTHtraceAll-PSTHtraceBase;

%%

OutTBLAll=[];
PSTHall=[];
ROIall=[];
MPFrameJump=1; %%mat file generated by ROI extraction (Python) already remove the frames syn. with MP, no need to delete the data
for iFile=1:length(binName)
    % tic
    clear OutTBL
    OutTBL=MPSeqFolder_1TargetXNon([DataFolder tifFolder{iFile} '\'],confSet,Pos3Dneed);
    OutTBL.FileID=fileIDList(iFile)*ones(size(OutTBL,1),1);
    OutTBLAll=[OutTBLAll;OutTBL];
    planePos=round(Pos3Dneed(OutTBL.Point,3));
    [~,planeI]=ismember(planePos,planeDepth);


    [indexVector, stimulusIDVector, prePostStimuliVector] = getPSTHFrames_MPxmlInfo(OutTBL, PreSLMCal, PostSLMCal,MPFrameJump);
    PSTHmap = CalMultiPSTHBin([DataFolder binName{iFile}], confSet, indexVector, stimulusIDVector, prePostStimuliVector);
    PSTHall=cat(3,PSTHall,PSTHmap);
% figure;
% MultiPlanes2DShow(tempData, [], Pos3Dneed(OutTBL.Point(iP),:), [], confSet.scan_Z(1)+confSet.ETL, [0,1,0], [-300 300]);
% colormap(colorMapPN1)
   for iP=1:size(OutTBL,1)
       Point=OutTBL.Point(iP);
       roiHeat=Center2neighbour(PSTHmap(:,:,iP,planeI(iP)),Pos3Dneed(Point,[1,2]),NeighbourHfWidthPixel);
       roiHeat=SmoothDecDim3(roiHeat,[1 1])';
       % roiHeat=roiHeat';
       ROIall=cat(3,ROIall,roiHeat);
   end
   clear PSTHmap roiHeat;
   % toc
end

%%


SLMTrialInfo=OutTBLAll;
SLMTrialInfo.Laser=PVpower2xmlPower(SLMTrialInfo.UncagingLaserPower);
PointAll=unique(OutTBLAll.Point);
umPerPixel=mean([yaml.umPerlPixelX yaml.umPerlPixelY]);
%param for ROI neighbourhood to determine wether there is SLM response.
ROIparam.TotalSLMPos3D=Pos3Dneed;    %%such that ROIparam.PointAll=1:size(Pos3Dneed,1)
ROIparam.PointAll=PointAll;
% ROIparam.PlaneZ=PlaneZ;
ROIparam.CellSize=20;                %%normal neuron diameter by um;        
ROIparam.threshold_percentage=0.3;   %%thereshold to define responsive fields SLM responsive heatmap: percentage*Peak rate
ROIparam.thNum=10;                   %%Minimal single responsive field by pixels
ROIparam.max_distance=ceil(ROIparam.CellSize/3/umPerPixel);  %% 2/3 diameter of a cell by pixel as maximal response region-SLM center distance
ROIparam.min_region_size=5;
ROIparam.PeakTh=200;
ROIparam.min_merged_region_size=40;  %%Minimal total size of responsive fields by pixels
ROIparam.contourMethod='boundaries';      %%Method to detect ROI boader of responsive fields
ROIparam.NeighbourHfWidthPixel=20;   %%PixFromMedCenter: Number of pixels from the median center of each ROI to get the ROI neighborhood.
ROIparam.umPerPixel=umPerPixel;
ROIparam.Colormap=colorMapPN1;                  
ROIparam.LaserPower=confSet.UncagingLaserPower;  
ROIparam.LaserPower=SLMTrialInfo.Laser;  

ROIparam.PointsTest=PointAll;
ROIparam.Clim=[-400;400];

PSTHparam.PointAll=ROIparam.PointAll;
PSTHparam.PreSLMCal=PreSLMCal;
PSTHparam.PostSLMCal=PostSLMCal;
PSTHparam.PointsTest=ROIparam.PointsTest;
PSTHparam.LaserPower=ROIparam.LaserPower;
PSTHparam.YLim=[-50 600];       % %<-----------------------------------------For Suite2p based ROI signal only method
PSTHparam.pTh=0.05;             % %<-----------------------------------------For Suite2p based ROI signal only method
PSTHparam.TestMethod='ranksum'; % %<-----------------------------------------For Suite2p based ROI signal only method

PreSLMCal=15;                 %<----------------------------------------------------------------------------------Edit,Frame # before SLM to calculate baseline map
PostSLMCal=3;                 %<----------------------------------------------------------------------------------Edit,Frame # after SLM to calculate responsive map


XMLparam.SwitchXMLPostMPFrame=6;                   %%<-----------MarkPoint switching occurs after 10 Repetitions of nplanes of Zseries.
XMLparam.ProcessFolder=ProcessFolder;

XMLparam.RoundID=6;
XMLparam.PointList=[1:10];                     %%<-----------nP, NumOfTestedPoints, nP + 1 = NumOfZseries 
XMLparam.Laser=[repmat(1.4,1,10)] ;                  %%<-----------laser values, could be 1 value of a vector with length of nP
XMLparam.TotalRounds=confSet.NumTrial;


nPlane=3;

PowerTestPVPar.nPlane=nPlane;            
PowerTestPVPar.ZRepetition=51;                      %%<-----------NumOfRepeition in each Zseries of Tseries in PV
PowerTestPVPar.Ziteration=11;                        %%<-----------NumOfZseries in Tseries in PV
PowerTestPVPar.InterMPRepetition=repmat(PowerTestPVPar.ZRepetition,1,PowerTestPVPar.Ziteration);
frameRepetition=PowerTestPVPar.ZRepetition*PowerTestPVPar.Ziteration;
PowerTestPVPar.maxFrame=nPlane*frameRepetition;
% PowerTestPVPar.BreakPointFrame=PowerTestPVPar.InterMPRepetition(1:end-1)*nPlane;
% PowerTestPVPar.InterMPFrame=[40 60 30 20]*nPlane;
% PowerTestPVPar.TrialMPSwitch=length(PowerTestPVPar.InterMPRepetition)-1;


%%

minTrialN=4;

for IEnd=2:18
FileIDrange=[2;IEnd];
FileIDrange=[3;36]
[SLMRes,sampleN]=SLMResponse_ROIMultiZ(ROIall,SLMTrialInfo,ROIparam,minTrialN,SumDataFolder,FileIDrange);
[SLMResTrace,sampleNTrace]=SLMResponse_PSTHTraceMultiZ(PSTHTraceN,SLMTrialInfo,PSTHparam,minTrialN,SumDataFolder,FileIDrange);
close all
end
[SLMRes,sampleN]=SLMResponse_ROIMultiZ(ROIall,SLMTrialInfo,ROIparam,minTrialN,SumDataFolder,FileIDrange);

% [SLMResTrace,sampleNTrace,SLMRatio,SLMpVal]=SLMResponse_PSTHTraceMultiZ(PSTHTraceN,SLMTrialInfo,PSTHparam,minTrialN,SumDataFolder,FileIDrange);

SLMTrialInfo=[];                  %Inital response information, automatically updated after each single trial test
SLMTrialMap=[];                   %Inital response map, automatically updated after each single trial test
clear SLMTable;
SLMTable(:,1)=round(1:size(Pos3Dneed,1));
SLMTable(:,2)=NaN;


close all
FileIDrange=[2;14];
[SLMRes,sampleN]=SLMResponse_ROIMultiZ(ROIall,SLMTrialInfo,ROIparam,minTrialN,SumDataFolder,FileIDrange);

PointLaserPair = SelectPointsForTesting_v3(SLMRes, sampleN, SLMTestParam, PowerTestPVPar.Ziteration-1);
if isempty(PointLaserPair)
   disp('Terminate the power test')
else
   
end

XMLparam.PointList=PointLaserPair(:,1);
XMLparam.Laser=ROIparam.LaserPower(PointLaserPair(:,2));
[XMLTable{iCount},FileGenerateInfo(iCount)]=PV_LinkPowerTest_MultiZseries(XMLparam,PowerTestPVPar);


clear SLMTable;
SLMTable(:,1)=round(1:size(Pos3Dneed,1));
SLMTable(:,2)=NaN;
SLMTestParam.TerminalTrialN=4;    %<-------------------------------------------------------------------------------Edit, Trials # to define SLM responsive cells
SLMTestParam.ExcludeTrialN=2;     %<-------------------------------------------------------------------------------Edit, Trials # to define Non-SLM responsive cells
SLMTestParam.AllLaserPower=confSet.UncagingLaserPower;

FileIDrange=[2;2];
[SLMRes,sampleN]=SLMResponse_ROIMultiZ(ROIall,SLMTrialInfo,ROIparam,minTrialN,SumDataFolder,FileIDrange);

[UpdateXml, SLMTable, PointsTest, XMLparam, InfoListByLaser]=step3Fun_NextSLMtest(SLMRes,sampleN,ROIparam,XMLparam,SLMTestParam,SLMTable);






figure;
imagesc(roiHeat)
set(gca,'clim',[-400 400]);
colormap(colorMapPN1)

